# Generated by Django 5.2.9 on 2025-12-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vshop', '0005_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images/'),
        ),
    ]
